/**
 * The photographic surface detail: which map goes on what, and how big it tiles.
 *
 * Everything here is fetched by `tools/textures/fetch.py` from ambientCG (CC0)
 * or generated by it, and committed under `src/assets/textures/` with its
 * provenance in `ATTRIBUTION.md` beside it. 426 KB in twelve files.
 *
 * ============================================================
 * WHAT A TEXTURE IS ACTUALLY BUYING HERE
 * ============================================================
 *
 * Not colour. The cast was already the right colours — eight outfits chosen to
 * be different from each other, in `figures.ts`, and a head shaded per vertex
 * out of the same primitives as the sculpt. What it was NOT was any particular
 * MATERIAL: every surface reflected the key light by exactly the same amount at
 * every point, so a jacket, a shirt, a desk and a forehead were all the same
 * substance in four colours. `microRoughness` in `human.ts` broke the highlight
 * up a little, and a uniform ±12% of noise is the difference between plastic
 * and slightly worn plastic.
 *
 * What separates wool from plastic at three metres is RELIEF — a weave, a grain,
 * a pile, pores — and relief is a normal map. So:
 *
 *  * a garment gets a NORMAL map and keeps its own albedo. A downloaded colour
 *    map there would overwrite six people's wardrobes with one jacket;
 *  * the studio's surfaces get COLOUR as well, because a desk is walnut and a
 *    floor is studio carpet and neither is anybody's palette;
 *  * skin gets pore relief and hair gets strand relief, both GENERATED, because
 *    one has to be feature-agnostic and the other has to run with the head.
 *
 * ============================================================
 * WHY NO FACE PHOTOGRAPH, WHICH IS THE ONE THING NOT DONE HERE
 * ============================================================
 *
 * A texture needs UV coordinates. The head is `CreateSphere` whose vertices are
 * then moved into a face by `sculptHeadVertex`, so the UVs it carries are the
 * SPHERE's: after the sculpt they correspond to no feature at all. A face
 * photograph on it lands an eye on a cheek and a mouth on a jaw, at every scale
 * and every tiling — it needs a feature-aligned unwrap, which is a modelling
 * artefact and not something a fetch can produce. `skinShadeAt` does the job a
 * colour map would do, per vertex, from the same primitives as the shape, which
 * is the one way the shading cannot drift from the features.
 *
 * Pore RELIEF has no such requirement, because a pore is in the same place
 * whichever way round the map lands. That is the half that is applied.
 *
 * ============================================================
 * ONE TEXTURE PER SCENE, NOT ONE PER FIGURE
 * ============================================================
 *
 * Eight figures in the meeting means eight jackets, eight shirts and eight
 * heads. Constructing a `Texture` per material is eight fetches of one URL
 * (which the HTTP cache absorbs) and, far worse, eight GPU uploads of the same
 * image — so every map is cached on the scene under a key, exactly as
 * `microRoughness` already is. The cache lives on the scene rather than in a
 * module-level map because a scene is disposed and its textures with it; a
 * module-level cache would hand a disposed texture to the next stage.
 */

import type { Scene } from '@babylonjs/core/scene';
import type { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial';
import type { Texture } from '@babylonjs/core/Materials/Textures/texture';

import type * as BJS from './babylon';

import clothWoolNormal from '@/assets/textures/cloth-wool-normal.jpg';
import clothShirtNormal from '@/assets/textures/cloth-shirt-normal.jpg';
import skinDetailNormal from '@/assets/textures/skin-detail-normal.jpg';
import hairStrandNormal from '@/assets/textures/hair-strand-normal.jpg';
import studioPlasterColour from '@/assets/textures/studio-plaster-colour.jpg';
import studioPlasterNormal from '@/assets/textures/studio-plaster-normal.jpg';
import studioWoodColour from '@/assets/textures/studio-wood-colour.jpg';
import studioWoodNormal from '@/assets/textures/studio-wood-normal.jpg';
import studioCarpetColour from '@/assets/textures/studio-carpet-colour.jpg';
import studioCarpetNormal from '@/assets/textures/studio-carpet-normal.jpg';
import studioMetalColour from '@/assets/textures/studio-metal-colour.jpg';
import studioMetalNormal from '@/assets/textures/studio-metal-normal.jpg';

/**
 * Every map, by name.
 *
 * These are only the URL strings until something asks for one — an `import` of
 * an image in Vite compiles to a hashed path, so all twelve of these cost about
 * seven hundred bytes in the chunk and the JPEGs are fetched when a `Texture` is
 * constructed. Which is what makes it safe for this module to be imported
 * eagerly by `human.ts` and `setPieces.ts`: those two are themselves only
 * reachable through `loadStage3d()`, and within them nothing is downloaded that
 * is not put on a mesh.
 */
export const TEXTURE_URLS = {
    'cloth-wool': clothWoolNormal,
    'cloth-shirt': clothShirtNormal,
    'skin-detail': skinDetailNormal,
    'hair-strand': hairStrandNormal,
    'plaster-colour': studioPlasterColour,
    'plaster-normal': studioPlasterNormal,
    'wood-colour': studioWoodColour,
    'wood-normal': studioWoodNormal,
    'carpet-colour': studioCarpetColour,
    'carpet-normal': studioCarpetNormal,
    'metal-colour': studioMetalColour,
    'metal-normal': studioMetalNormal,
} as const;

export type TextureName = keyof typeof TEXTURE_URLS;

/**
 * How many times each map repeats across one metre of surface.
 *
 * A tiling figure, not a UV scale, and the difference matters: the meshes here
 * are metres across and their UVs run 0..1 over the whole mesh, so a fixed
 * `uScale` puts a 2 mm weave on a 12 cm sleeve and a 2 cm weave on a 4 m
 * cyclorama. Every caller passes the size of the thing it is texturing and gets
 * a weave that is the same size on every surface — which is the property that
 * makes it read as cloth rather than as a pattern.
 *
 * The numbers are the real-world size of one tile of each source, inverted:
 * ambientCG's `Fabric032` is a 20 cm patch, so it repeats five times a metre.
 */
const REPEATS_PER_METRE: Record<TextureName, number> = {
    'cloth-wool': 26,
    'cloth-shirt': 34,
    // Pores. Fine enough that the map is well past the pixels it lands on at
    // tile framing, and that is the right way round: too coarse reads as acne.
    'skin-detail': 190,
    // A hair patch is ~4 cm of scalp. Tighter than that and the strands alias
    // into a shimmer as the head turns.
    'hair-strand': 22,
    'plaster-colour': 0.55,
    'plaster-normal': 0.55,
    'wood-colour': 1.1,
    'wood-normal': 1.1,
    'carpet-colour': 1.6,
    'carpet-normal': 1.6,
    'metal-colour': 3.2,
    'metal-normal': 3.2,
};

interface TextureCache {
    [key: string]: Texture;
}

/**
 * One shared, mipmapped, wrapping texture per (scene, name, tiling).
 *
 * The tiling is part of the key because `uScale` lives on the TEXTURE and not
 * on the material: a desk and a cyclorama both want plaster at different sizes,
 * and sharing one instance between them would make whichever was built second
 * silently re-scale the first. That is a bug with no error and no obvious cause
 * — the classic symptom is a wall whose grain suddenly matches a table's.
 */
export function textureFor(
    B: typeof BJS, scene: Scene, name: TextureName, metres: number,
    metresV = metres,
): Texture {
    /*
      TWO AXES, BECAUSE ONE OF THEM IS NOT ENOUGH FOR A CYLINDER.

      Most meshes here are roughly square in UV terms and one figure serves both
      axes. Two are not, and both are large enough that getting it wrong is the
      only thing anybody would see: the cyclorama's UVs run once round its 56 m
      circumference and once up its 9 m height, and the desk top's run over 6.2 m
      by 0.60 m. Given one figure, the plaster comes out stretched six to one --
      which does not read as coarse plaster, it reads as BRUSHED METAL, because a
      stretched isotropic noise is exactly what an anisotropic surface looks like.

      Defaulting `metresV` to `metres` keeps every square caller unchanged.
    */
    const repeats = Math.max(0.05, REPEATS_PER_METRE[name] * metres);
    const repeatsV = Math.max(0.05, REPEATS_PER_METRE[name] * metresV);
    const key = `${name}@${repeats.toFixed(3)}x${repeatsV.toFixed(3)}`;
    const cache: TextureCache = (scene as any).__sfsTextures ??= {};
    const held = cache[key];
    if (held) return held;

    /*
      `invertY` is left at Babylon's default (true) DELIBERATELY.

      Babylon's own convention is OpenGL normal maps loaded with Y inverted —
      which is what glTF assets are and what every material in the engine
      assumes — and `fetch.py` already converts ambientCG's DirectX green
      channel to match. Setting `invertY: false` here to "fix" the flip would
      put the two halves of the convention out of step, and the result is not an
      upside-down texture: it is relief lit from the wrong side, which reads as
      a grubby surface rather than as anything inverted.
    */
    const texture = new B.Texture(TEXTURE_URLS[name], scene);
    texture.wrapU = 1; // WRAP_ADDRESSMODE
    texture.wrapV = 1;
    texture.uScale = repeats;
    texture.vScale = repeatsV;
    /*
      Anisotropic filtering, for the same reason `microRoughness` asks for it:
      almost every one of these surfaces is seen at a grazing angle somewhere in
      frame — a desk top, a floor, the side of a sleeve — and that is exactly
      where a tiled map without it turns into a shimmering band.
    */
    texture.anisotropicFilteringLevel = 4;
    cache[key] = texture;
    return texture;
}

/**
 * Put a normal map on a material.
 *
 * A function rather than two lines at each call site because of `level`: a
 * normal map at full strength is almost always too much. A weave photographed
 * flat-on carries relief sized for a close-up, and at 180 px of tile it reads as
 * a crumpled bin bag rather than as wool. Every caller here passes something
 * between 0.25 and 1.
 */
export function applyNormal(
    B: typeof BJS, scene: Scene, material: PBRMaterial,
    name: TextureName, metres: number, level = 1, metresV = metres,
): void {
    material.bumpTexture = textureFor(B, scene, name, metres, metresV);
    material.bumpTexture.level = level;
    /*
      NOT `invertNormalMapY`. See `textureFor` — the convention is settled at
      fetch time and in the loader, and a third place to flip it is a third
      place for two of them to cancel out.
    */
}

/**
 * Put a colour map on a material, TINTED by whatever colour it already had.
 *
 * `albedoTexture` REPLACES `albedoColor` in Babylon's PBR unless the two are
 * multiplied, and multiplied is what is wanted for every surface in the studio:
 * the walnut, the carpet and the plaster all arrive as a photograph of one
 * particular piece of one particular material, and the set needs them to sit in
 * the palette the room was lit for. So the material keeps its hex as a tint and
 * the photograph supplies the variation.
 *
 * `useAlphaFromAlbedoTexture` is left off: these are JPEGs with no alpha, and
 * switching it on moves the mesh into the transparent render list, which on a
 * floor means the desk sorting in front of it at some camera angles.
 */
export function applyColour(
    B: typeof BJS, scene: Scene, material: PBRMaterial,
    name: TextureName, metres: number, metresV = metres,
): void {
    material.albedoTexture = textureFor(B, scene, name, metres, metresV);
    material.useAlphaFromAlbedoTexture = false;
}
