<template>
  <div class="tm-page">
    <div class="tm-form-card">
      <h1>🎯 Prepare Your Session</h1>
      <p>Choose your speech type and configure today's session.</p>
      <form @submit.prevent="startSession">
        <label>Speech Type *</label>
        <select v-model="form.type" @change="updateType" required>
          <option value="Prepared Speech">Prepared Speech</option>
          <option value="Table Topics (Impromptu)">Table Topics (Impromptu)</option>
          <option value="Ice Breaker">Ice Breaker (First Speech)</option>
          <option value="Evaluation Speech">Evaluation Speech</option>
          <option value="Inspirational Speech">Inspirational Speech</option>
          <option value="Persuasive Speech">Persuasive Speech</option>
        </select>

        <div class="tm-type-info" v-html="typeInfo"></div>

        <div v-if="needsTopic">
          <label>Speech Topic / Title *</label>
          <input v-model="form.topic" placeholder="e.g., The Power of Daily Habits" :required="needsTopic">
        </div>

        <div class="tm-row">
          <div>
            <label>Min Duration (min)</label>
            <input type="number" v-model.number="form.min_time" min="1" max="60" required>
          </div>
          <div>
            <label>Max Duration (min)</label>
            <input type="number" v-model.number="form.max_time" min="1" max="60" required>
          </div>
        </div>

        <p class="tm-hint">⚠️ The next page will request camera and microphone permission.</p>
        <button type="submit" class="tm-btn-primary">Join Meeting →</button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

const TYPE_INFO: Record<string, { info: string; min: number; max: number; needsTopic: boolean }> = {
  'Prepared Speech': { info: '📝 Deliver a prepared speech on your topic. Speech Evaluator will check topic alignment.', min: 5, max: 7, needsTopic: true },
  'Table Topics (Impromptu)': { info: '⚡ The Toastmaster gives you an impromptu question. <strong>Topic generated automatically.</strong>', min: 1, max: 2, needsTopic: false },
  'Ice Breaker': { info: '🌱 Your first speech — talk about yourself. <strong>Camera must be on.</strong>', min: 4, max: 6, needsTopic: true },
  'Evaluation Speech': { info: '🎯 Practice being a Speech Evaluator. A bot delivers a speech; you evaluate it.', min: 2, max: 3, needsTopic: false },
  'Inspirational Speech': { info: '💫 Lift your audience with emotional stories and vivid imagery.', min: 5, max: 7, needsTopic: true },
  'Persuasive Speech': { info: '🎯 Convince with facts and a clear call to action.', min: 5, max: 7, needsTopic: true }
};

const form = reactive({
  type: 'Prepared Speech',
  topic: '',
  min_time: 5,
  max_time: 7
});

const typeInfo = computed(() => TYPE_INFO[form.type]?.info || '');
const needsTopic = computed(() => TYPE_INFO[form.type]?.needsTopic || false);

function updateType() {
  const cfg = TYPE_INFO[form.type];
  if (cfg) {
    form.min_time = cfg.min;
    form.max_time = cfg.max;
    if (!cfg.needsTopic) form.topic = cfg.needsTopic ? form.topic : 'Auto-generated';
  }
}

function startSession() {
  const topic = needsTopic.value ? form.topic : (form.type === 'Table Topics (Impromptu)' ? 'Auto-generated by Toastmaster' : 'Evaluation Practice');
  router.push({
    path: '/toastmasters/session',
    query: {
      type: form.type,
      topic: topic,
      min_time: String(form.min_time),
      max_time: String(form.max_time)
    }
  });
}

updateType();
</script>

<style src="@/assets/css/toastmasters.css"></style>